---
apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    key: value
spec: 
  containers: 
  - name: first-pod
    image: 123456789027071976/k8s:v1.0
  initContainers:
  - name: init-container
    image: busybox:1.31.0
    command: ['sh', '-c', 'wget -O- https://raw.githubusercontent.com/express42/otus-platformsnippets/master/Module-02/Introduction-to-Kubernetes/wget.sh | sh']
    volumeMounts:
    - name: app
      mountPath: /app
  volumes:
  - name: app
    emptyDir: {}  
  

